// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"cloud.google.com/go/firestore"
	"context"
	"local.packages/handler"
	"local.packages/plan"
	"local.packages/src"
)

// Injectors from wire.go:

func InitializeServer(client *firestore.Client, ctx context.Context) (*src.Server, error) {
	repositoryInterface := Plan.NewRepository(client, ctx)
	serviceInterface := Plan.NewService(repositoryInterface)
	planHandler := Handler.NewPlanHandler(serviceInterface)
	server := src.NewServer(planHandler)
	return server, nil
}
